---
#ansible/roles/vault/tasks/download.yml

# see https://www.hashicorp.com/security/
- name: Copy hashicorp key
  copy:
    src: hashicorp.asc
    dest: /tmp/hashicorp.asc

- name: Verify key was copied
  stat:
    path: /tmp/hashicorp.asc
  register: hashicorp_key

- name: Import hashicorp key
  command: gpg --import /tmp/hashicorp.asc
  when: hashicorp_key.stat.exists

- name: Get the checksum file
  get_url:
    url: "{{ vault_sums_download }}"
    dest: "/tmp/{{vault_sums}}"
  register: get_checksum

- name: Get the signature file
  get_url:
    url: "{{ vault_signature_download }}"
    dest: "/tmp/{{vault_signature}}"
  register: get_signature

- name: Verify hashicorp key
  command: gpg --verify {{ vault_signature }} {{ vault_sums }}
  args:
    chdir: /tmp
  when: get_checksum.status_code == 200 and get_signature.status_code == 200

- name: Get the zip file
  get_url:
    url: "{{ vault_download }}"
    dest: "/tmp/{{vault_archive}}"
  register: zip_download

- name: Verify zip
  shell: grep {{ vault_archive}} {{vault_sums}} | sha256sum -c
  args:
    chdir: /tmp/
  when: zip_download.status_code == 200
