---
# File: tasks/main.yml - Main tasks for Vault

- name: "Add Vault user"
  user:
    name: "{{ vault_user }}"
    comment: "Vault user"
    group: "{{ vault_group }}"
    system: yes

- name: Is vault installed
  stat:
    path: "{{ vault_bin_path }}/vault"
  register: vault_executable

- block:
   - name: Download Vault
     include: download.yml

   - name: Install Vault
     include: install.yml

   - name: Start Vault
     service:
       name: vault
       state: started
       enabled: yes

   - name: Is the vault API reachable?
     wait_for:
       host: "{{ vault_address}}"
       port: "{{ vault_port }}"
       delay: "10"
  when: not vault_executable.stat.exists
